---
## General
jboss_eap_version: "7.3"
project: "TEST"

## Service options
# Owner
jboss_eap_user: jboss
jboss_eap_group: jboss
jboss_eap_user_home: "/home/{{ jboss_eap_user }}"
jboss_eap_user_shell: "/bin/sh"
jboss_eap_user_uid: 1005

# start on boot
jboss_eap_service_enabled: True
# current state: started, stopped
jboss_eap_service_state: started

# Files & Paths
jboss_eap_install_path: "/opt/RH"
jboss_eap_home_path: "{{ jboss_eap_install_path }}/jboss-eap-{{ jboss_eap_version }}"
jboss_eap_deploy_dir_path: "{{ jboss_eap_home_path }}/standalone/deployments"

# Network
jboss_eap_bind: 0.0.0.0

# Management
jboss_eap_management_user: jboss
jboss_eap_management_password: password